[project]
name = "pinsky"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bregy Malpartida <bregy@minsky.cc>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
numpy = "1.26.0.*"
scikit-learn = "1.3.2.*"
matplotlib = "3.8.1.*"
umap-learn = "0.5.4.*"
hdbscan = "0.8.33.*"
pandas = "2.1.3.*"
ipykernel = "6.26.0.*"
bokeh = "3.3.1.*"
scikit-image = "0.22.0.*"
datashader = "0.16.0.*"
holoviews = "1.18.1.*"
colorcet = "3.0.1.*"
